created challenge object, passing it to search activity
cito125/AugHunt pull request #8
Opened 2017-03-04 07:00 UTC by Mila2010

2017-03-04 21:08 UTC, cito125 requested changes
# Resolve merge conflicts
- Run a `git pull origin master`
- Followed by a`git checkout Mila`
- Then `git rebase master`
  - Resolve conflicts
- Finally, push your changes for a review

2017-03-04 22:17 UTC, Mila2010 commented
resolved conflicts and pushed to Mila again

2017-03-06 16:41 UTC, cito125 requested changes

2017-03-06 16:41 UTC, cito125 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".homescreen.HomeScreenActivity">
There's a merge conflict on where we're starting the app with the intent filter : (

2017-03-06 16:41 UTC, cito125 commented on app/src/main/java/com/example/andresarango/aughunt/challenge/Challenge.java
> +public final class Challenge<T> {
Should the entire class be final?

2017-03-08 00:17 UTC, cito125 approved these changes

2017-03-08 00:18 UTC, closed without merging

2017-03-08 00:18 UTC, cito125 commented
I accidentally approved this, I apologize